# -*- coding: utf-8 -*-
"""221111_count_starbucks.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PzxqEO5-Y58drr8jjdqFjE-L0v9-_nuV
"""

import pandas as pd

temp = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/소상공인시장진흥공단_상가(상권)정보_경기_202209.csv',encoding ='utf-8')
temp

data = temp[['상호명', '지점명', '상권업종대분류명', '상권업종중분류명', '시도명', '시군구명', '행정동명']]
data

temp.info()

del temp

data.head()

# 중복제거
set(data['상권업종중분류명'])

# 카페만 뽑아냄
df_coffee = data[data['상권업종중분류명'] == '커피점/카페']
# print (df_coffee.index)
# 인덱스 다시 세팅
df_coffee.index = range(len(df_coffee))
print ('커피전문점 점포 수: ',len(df_coffee))
df_coffee

df_stb = data[data['상호명'] == '스타벅스']
df_stb

# 상호명중에 스타벅스가 있니
df_coffee['상호명'].str.contains('스타벅스')

df_stb = df_coffee[df_coffee['상호명'].str.contains('스타벅스')]
df_stb.index = range(len(df_stb))
print ('스타벅스 점포 수: ',len(df_stb))
df_stb

# 수원시에 있는 카페 중 어떤 브랜드가 많을까

# 수원시 카페 수
df_suwon = df_coffee[df_coffee['시군구명'].str.contains('수원시')]
df_suwon.index = range(len(df_suwon))
print ('수원시 카페 수: ',len(df_suwon))
df_suwon

# 수원시 카페 전체에서 상호명 중복제거
cafe_name = set(df_suwon['상호명'])
len(cafe_name)

df_suwon.groupby('상호명').size()

# df_suwon['상호명'].value_counts()

# 상호명이 같은 원소의 개수
# df_suwon['상호명'].value_counts()

# 전체카페수
# len (df_suwon)

# 많은순으로 비율
# df_suwon['상호명'].value_counts() / len (df_suwon) *100

# 많은 순으로 비율, 상위 30개
(df_suwon['상호명'].value_counts() / len (df_suwon) *100).head(30)